REM $Header: create_xhume_script.sql 11.4.3.5 2011/08/10 carlos.sierra $
SET DEF ON TERM OFF ECHO OFF FEED OFF FLU OFF HEA OFF LIN 2000 NEWP NONE PAGES 0 SHOW OFF SQLC MIX TAB OFF TRIMS ON VER OFF TI OFF TIMI OFF ARRAY 100 SQLP SQL> BLO . RECSEP OFF APPI OFF SERVEROUT ON SIZE 1000000 FOR TRU;
SET SERVEROUT ON SIZE UNL FOR TRU;
SPO xhume_script.sql
EXEC xhume.create_xhume_script;
SPO OFF;
SET TERM ON;
