#!/bin/bash

##################################################通用数据恢复脚本################################################################################
#常量定义,程序中会替换为指定值之后执行 
DBTYPE=${dbtype}
SUBDBTYPE=${subdbtype}
BACKUPID=${backupid}
USER=${username}
PWD=${password}
HOST=${host}
PORT=${port}
DBNAME=${dbname}
CHARSET=${charset}
BACKUPDIR=${backupdir}
BUSINTYPE=${busintype}
BACKUPFLAG=${backupflag}
FILENAME=${filename}
PARALLEL=${parallel}
COMPRESSION=${compression}
TABLES="TBFUND"
BACKUPTABLES="${backuptables}"
TENANT=${tenant}
CLUSTER=${cluster}
BACKUPDATE=${backupdate}
#找到上级目录的func文件
SHELLPATH=${shellpath}
BACKUPMODE=${backupmode}

source $SHELLPATH/func

if [ "$BACKUPMODE" == "0" ];then
 if [ "$DBTYPE" == "oracle" ] && [ "$SUBDBTYPE" == "dm" ];then
		expdb $FILENAME$BACKUPFLAG$BUSINTYPE.dmp TBFUNDINCOMEHIS TBFUNDINTFECHANGE05FILEHIS TBFUNDINTFECHANGESYHIS TBFUNDPRFTFLOWDTLHIS TBFUNDPRFTFLOWHIS TBFUNDSHARECHGHIS TBFUNDSUBSCONFIRMHIS TBFUNDTACFMDETAILHIS TBFUNDTADIVDETAILHIS TBFUNDTATRANSCFMHIS TBFUNDTATRANSREQHIS TBFUNDUNSENDDIVHIS TBTAACCCFMHIS
 elif [ "$DBTYPE" == "mysql" ] && [ "$SUBDBTYPE" == "pg" ];then
		expdb $BACKUPDIR/$FILENAME$BACKUPFLAG$BUSINTYPE  TBFUNDINCOMEHIS TBFUNDINTFECHANGE05FILEHIS TBFUNDINTFECHANGESYHIS TBFUNDPRFTFLOWDTLHIS TBFUNDPRFTFLOWHIS TBFUNDSHARECHGHIS TBFUNDSUBSCONFIRMHIS TBFUNDTACFMDETAILHIS TBFUNDTADIVDETAILHIS TBFUNDTATRANSCFMHIS TBFUNDTATRANSREQHIS TBFUNDUNSENDDIVHIS TBTAACCCFMHIS
 elif [ "$DBTYPE" == "mysql" ] && [ "$SUBDBTYPE" == "lightdb" ];then
		expdb $BACKUPDIR/$FILENAME$BACKUPFLAG$BUSINTYPE  TBFUNDINCOMEHIS TBFUNDINTFECHANGE05FILEHIS TBFUNDINTFECHANGESYHIS TBFUNDPRFTFLOWDTLHIS TBFUNDPRFTFLOWHIS TBFUNDSHARECHGHIS TBFUNDSUBSCONFIRMHIS TBFUNDTACFMDETAILHIS TBFUNDTADIVDETAILHIS TBFUNDTATRANSCFMHIS TBFUNDTATRANSREQHIS TBFUNDUNSENDDIVHIS TBTAACCCFMHIS
 elif [ "$DBTYPE" == "oracle" ] && [ "$SUBDBTYPE" == "oceanbase" ];then
		expdb $BACKUPDIR/$FILENAME$BACKUPFLAG$BUSINTYPE  TBFUNDINCOMEHIS TBFUNDINTFECHANGE05FILEHIS TBFUNDINTFECHANGESYHIS TBFUNDPRFTFLOWDTLHIS TBFUNDPRFTFLOWHIS TBFUNDSHARECHGHIS TBFUNDSUBSCONFIRMHIS TBFUNDTACFMDETAILHIS TBFUNDTADIVDETAILHIS TBFUNDTATRANSCFMHIS TBFUNDTATRANSREQHIS TBFUNDUNSENDDIVHIS TBTAACCCFMHIS
 elif [ "$DBTYPE" == "mysql" ];then
		expdb $BACKUPDIR/$FILENAME$BACKUPFLAG$BUSINTYPE.sql  TBFUNDINCOMEHIS TBFUNDINTFECHANGE05FILEHIS TBFUNDINTFECHANGESYHIS TBFUNDPRFTFLOWDTLHIS TBFUNDPRFTFLOWHIS TBFUNDSHARECHGHIS TBFUNDSUBSCONFIRMHIS TBFUNDTACFMDETAILHIS TBFUNDTADIVDETAILHIS TBFUNDTATRANSCFMHIS TBFUNDTATRANSREQHIS TBFUNDUNSENDDIVHIS TBTAACCCFMHIS
 elif [ "$DBTYPE" == "oracle" ];then
		expdb $FILENAME$BACKUPFLAG$BUSINTYPE%U.dmp  TBFUNDINCOMEHIS TBFUNDINTFECHANGE05FILEHIS TBFUNDINTFECHANGESYHIS TBFUNDPRFTFLOWDTLHIS TBFUNDPRFTFLOWHIS TBFUNDSHARECHGHIS TBFUNDSUBSCONFIRMHIS TBFUNDTACFMDETAILHIS TBFUNDTADIVDETAILHIS TBFUNDTATRANSCFMHIS TBFUNDTATRANSREQHIS TBFUNDUNSENDDIVHIS TBTAACCCFMHIS
 else
    echo "数据库类型不匹配"
    exit -1
 fi
elif [ "$BACKUPMODE" == "1" ];then
 if [ "$DBTYPE" == "oracle" ] && [ "$SUBDBTYPE" == "dm" ];then
	if [ "$BACKUPTABLES" == "" ]; then
		expdb $FILENAME$BACKUPFLAG$BUSINTYPE.dmp TBFUNDINCOMEHIS TBFUNDINTFECHANGE05FILEHIS TBFUNDINTFECHANGESYHIS TBFUNDPRFTFLOWDTLHIS TBFUNDPRFTFLOWHIS TBFUNDSHARECHGHIS TBFUNDSUBSCONFIRMHIS TBFUNDTACFMDETAILHIS TBFUNDTADIVDETAILHIS TBFUNDTATRANSCFMHIS TBFUNDTATRANSREQHIS TBFUNDUNSENDDIVHIS TBTAACCCFMHIS
	else
	    exptable $FILENAME$BACKUPFLAG$BUSINTYPE.dmp TBFUNDINCOMEHIS TBFUNDINTFECHANGE05FILEHIS TBFUNDINTFECHANGESYHIS TBFUNDPRFTFLOWDTLHIS TBFUNDPRFTFLOWHIS TBFUNDSHARECHGHIS TBFUNDSUBSCONFIRMHIS TBFUNDTACFMDETAILHIS TBFUNDTADIVDETAILHIS TBFUNDTATRANSCFMHIS TBFUNDTATRANSREQHIS TBFUNDUNSENDDIVHIS TBTAACCCFMHIS
	fi
 elif [ "$DBTYPE" == "mysql" ] && [ "$SUBDBTYPE" == "pg" ];then
		expdb $BACKUPDIR/$FILENAME$BACKUPFLAG$BUSINTYPE TBFUNDINCOMEHIS TBFUNDINTFECHANGE05FILEHIS TBFUNDINTFECHANGESYHIS TBFUNDPRFTFLOWDTLHIS TBFUNDPRFTFLOWHIS TBFUNDSHARECHGHIS TBFUNDSUBSCONFIRMHIS TBFUNDTACFMDETAILHIS TBFUNDTADIVDETAILHIS TBFUNDTATRANSCFMHIS TBFUNDTATRANSREQHIS TBFUNDUNSENDDIVHIS TBTAACCCFMHIS
 elif [ "$DBTYPE" == "mysql" ] && [ "$SUBDBTYPE" == "lightdb" ];then
		expdb $BACKUPDIR/$FILENAME$BACKUPFLAG$BUSINTYPE TBFUNDINCOMEHIS TBFUNDINTFECHANGE05FILEHIS TBFUNDINTFECHANGESYHIS TBFUNDPRFTFLOWDTLHIS TBFUNDPRFTFLOWHIS TBFUNDSHARECHGHIS TBFUNDSUBSCONFIRMHIS TBFUNDTACFMDETAILHIS TBFUNDTADIVDETAILHIS TBFUNDTATRANSCFMHIS TBFUNDTATRANSREQHIS TBFUNDUNSENDDIVHIS TBTAACCCFMHIS
 elif [ "$DBTYPE" == "oracle" ] && [ "$SUBDBTYPE" == "oceanbase" ];then
		expdb $BACKUPDIR/$FILENAME$BACKUPFLAG$BUSINTYPE TBFUNDINCOMEHIS TBFUNDINTFECHANGE05FILEHIS TBFUNDINTFECHANGESYHIS TBFUNDPRFTFLOWDTLHIS TBFUNDPRFTFLOWHIS TBFUNDSHARECHGHIS TBFUNDSUBSCONFIRMHIS TBFUNDTACFMDETAILHIS TBFUNDTADIVDETAILHIS TBFUNDTATRANSCFMHIS TBFUNDTATRANSREQHIS TBFUNDUNSENDDIVHIS TBTAACCCFMHIS
 elif [ "$DBTYPE" == "mysql" ];then
	if [ "$BACKUPTABLES" == "" ]; then
		expdb $BACKUPDIR/$FILENAME$BACKUPFLAG$BUSINTYPE.sql TBFUNDINCOMEHIS TBFUNDINTFECHANGE05FILEHIS TBFUNDINTFECHANGESYHIS TBFUNDPRFTFLOWDTLHIS TBFUNDPRFTFLOWHIS TBFUNDSHARECHGHIS TBFUNDSUBSCONFIRMHIS TBFUNDTACFMDETAILHIS TBFUNDTADIVDETAILHIS TBFUNDTATRANSCFMHIS TBFUNDTATRANSREQHIS TBFUNDUNSENDDIVHIS TBTAACCCFMHIS
	else
	    exptable $BACKUPDIR/$FILENAME$BACKUPFLAG$BUSINTYPE.sql TBFUNDINCOMEHIS TBFUNDINTFECHANGE05FILEHIS TBFUNDINTFECHANGESYHIS TBFUNDPRFTFLOWDTLHIS TBFUNDPRFTFLOWHIS TBFUNDSHARECHGHIS TBFUNDSUBSCONFIRMHIS TBFUNDTACFMDETAILHIS TBFUNDTADIVDETAILHIS TBFUNDTATRANSCFMHIS TBFUNDTATRANSREQHIS TBFUNDUNSENDDIVHIS TBTAACCCFMHIS
	fi
 elif [ "$DBTYPE" == "oracle" ];then
	if [ "$BACKUPTABLES" == "" ]; then
		expdb $FILENAME$BACKUPFLAG$BUSINTYPE%U.dmp TBFUNDINCOMEHIS TBFUNDINTFECHANGE05FILEHIS TBFUNDINTFECHANGESYHIS TBFUNDPRFTFLOWDTLHIS TBFUNDPRFTFLOWHIS TBFUNDSHARECHGHIS TBFUNDSUBSCONFIRMHIS TBFUNDTACFMDETAILHIS TBFUNDTADIVDETAILHIS TBFUNDTATRANSCFMHIS TBFUNDTATRANSREQHIS TBFUNDUNSENDDIVHIS TBTAACCCFMHIS
	else
	    exptable $FILENAME$BACKUPFLAG$BUSINTYPE%U.dmp TBFUNDINCOMEHIS TBFUNDINTFECHANGE05FILEHIS TBFUNDINTFECHANGESYHIS TBFUNDPRFTFLOWDTLHIS TBFUNDPRFTFLOWHIS TBFUNDSHARECHGHIS TBFUNDSUBSCONFIRMHIS TBFUNDTACFMDETAILHIS TBFUNDTADIVDETAILHIS TBFUNDTATRANSCFMHIS TBFUNDTATRANSREQHIS TBFUNDUNSENDDIVHIS TBTAACCCFMHIS
	fi
 else
    echo "数据库类型不匹配"
    exit -1
 fi
fi
#if [ "$DBTYPE" == "mysql" ];then
#    exptablelikes $BACKUPDIR/$FILENAME$BACKUPFLAG$BUSINTYPE.sql TBBACKUPINFO TBRESTOREINFO
#elif [ "$DBTYPE" == "oracle" ];then
#    exptablelikes $FILENAME$BACKUPFLAG$BUSINTYPE%U.dmp TBBACKUPINFO TBRESTOREINFO
#else
#    echo "数据库类型不匹配"
#    exit -1
#fi
