#!/bin/bash
##################################################通用数据恢复脚本################################################################################
#常量定义,程序中会替换为指定值之后执行 
DBTYPE=${dbtype}
SUBDBTYPE=${subdbtype}
BACKUPID=${backupid}
USER=${username}
PWD=${password}
HOST=${host}
PORT=${port}
DBNAME=${dbname}
CHARSET=${charset}
BACKUPDIR=${backupdir}
BUSINTYPE=${busintype}
BACKUPFLAG=${backupflag}
FILENAME=${filename}
PARALLEL=${parallel}
COMPRESSION=${compression}
TENANT=${tenant}
CLUSTER=${cluster}
BACKUPDATE=${backupdate}
SHELLPATH=${shellpath}
BACKUPMODE=${backupmode}

source $SHELLPATH/func

if [ "$BACKUPMODE" == "0" ];then
 if [ "$DBTYPE" == "oracle" ] && [ "$SUBDBTYPE" == "dm" ];then
		expdb $FILENAME$BACKUPFLAG$BUSINTYPE.dmp TBBACKUPINFO TBRESTOREINFO TBHISSCHEDULEPROCESS TBSCHEDULEPROCESS TBSCHEDULEAPPPROCESS TBSCHEDULEJOB TBSCHEDULETASK
 elif [ "$DBTYPE" == "mysql" ] && [ "$SUBDBTYPE" == "pg" ];then
		expdb $BACKUPDIR/$FILENAME$BACKUPFLAG$BUSINTYPE TBBACKUPINFO TBRESTOREINFO TBHISSCHEDULEPROCESS TBSCHEDULEPROCESS TBSCHEDULEAPPPROCESS TBSCHEDULEJOB TBSCHEDULETASK
 elif [ "$DBTYPE" == "mysql" ] && [ "$SUBDBTYPE" == "lightdb" ];then
	  expdb $BACKUPDIR/$FILENAME$BACKUPFLAG$BUSINTYPE TBBACKUPINFO TBRESTOREINFO TBHISSCHEDULEPROCESS TBSCHEDULEPROCESS TBSCHEDULEAPPPROCESS TBSCHEDULEJOB TBSCHEDULETASK TBLOGS TBSCHEDULETRIGGER TBSCHEDULELOCK
 elif [ "$DBTYPE" == "oracle" ] && [ "$SUBDBTYPE" == "oceanbase" ];then
		expdb $BACKUPDIR/$FILENAME$BACKUPFLAG$BUSINTYPE TBBACKUPINFO TBRESTOREINFO TBHISSCHEDULEPROCESS TBSCHEDULEPROCESS TBSCHEDULEAPPPROCESS TBSCHEDULEJOB TBSCHEDULETASK
 elif [ "$DBTYPE" == "mysql" ];then
       expdb $BACKUPDIR/$FILENAME$BACKUPFLAG$BUSINTYPE.sql TBBACKUPINFO TBRESTOREINFO TBHISSCHEDULEPROCESS TBSCHEDULEPROCESS TBSCHEDULEAPPPROCESS TBSCHEDULEJOB TBSCHEDULETASK
 elif [ "$DBTYPE" == "oracle" ];then
      expdb $FILENAME$BACKUPFLAG$BUSINTYPE%U.dmp TBBACKUPINFO TBRESTOREINFO TBHISSCHEDULEPROCESS TBSCHEDULEPROCESS TBSCHEDULEAPPPROCESS TBSCHEDULEJOB TBSCHEDULETASK
 else
    echo "数据库类型不匹配"
    exit -1
 fi
elif [ "$BACKUPMODE" == "1" ];then
 if [ "$DBTYPE" == "oracle" ] && [ "$SUBDBTYPE" == "dm" ];then
		exptablelikes $FILENAME$BACKUPFLAG$BUSINTYPE.dmp TBBACKUPINFO TBRESTOREINFO TBHISSCHEDULEPROCESS TBSCHEDULEPROCESS TBSCHEDULEAPPPROCESS TBSCHEDULEJOB TBSCHEDULETASK
 elif [ "$DBTYPE" == "mysql" ] && [ "$SUBDBTYPE" == "pg" ];then
		expdb $BACKUPDIR/$FILENAME$BACKUPFLAG$BUSINTYPE TBBACKUPINFO TBRESTOREINFO TBHISSCHEDULEPROCESS TBSCHEDULEPROCESS TBSCHEDULEAPPPROCESS TBSCHEDULEJOB TBSCHEDULETASK
 elif [ "$DBTYPE" == "mysql" ] && [ "$SUBDBTYPE" == "lightdb" ];then
	 exptablelikes $BACKUPDIR/$FILENAME$BACKUPFLAG$BUSINTYPE TBBACKUPINFO TBRESTOREINFO TBHISSCHEDULEPROCESS TBSCHEDULEPROCESS TBSCHEDULEAPPPROCESS TBSCHEDULEJOB TBSCHEDULETASK TBLOGS TBSCHEDULETRIGGER TBSCHEDULELOCK
 elif [ "$DBTYPE" == "oracle" ] && [ "$SUBDBTYPE" == "oceanbase" ];then
		expdb $BACKUPDIR/$FILENAME$BACKUPFLAG$BUSINTYPE TBBACKUPINFO TBRESTOREINFO TBHISSCHEDULEPROCESS TBSCHEDULEPROCESS TBSCHEDULEAPPPROCESS TBSCHEDULEJOB TBSCHEDULETASK
 elif [ "$DBTYPE" == "mysql" ];then
    exptablelikes $BACKUPDIR/$FILENAME$BACKUPFLAG$BUSINTYPE.sql TBBACKUPINFO TBRESTOREINFO TBHISSCHEDULEPROCESS TBSCHEDULEPROCESS TBSCHEDULEAPPPROCESS TBSCHEDULEJOB TBSCHEDULETASK
 elif [ "$DBTYPE" == "oracle" ];then
    exptablelikes $FILENAME$BACKUPFLAG$BUSINTYPE%U.dmp TBBACKUPINFO TBRESTOREINFO TBHISSCHEDULEPROCESS TBSCHEDULEPROCESS TBSCHEDULEAPPPROCESS TBSCHEDULEJOB TBSCHEDULETASK
 else
    echo "数据库类型不匹配"
    exit -1
 fi
fi

